#Aiden Fisher
version: '3'
services:
    flaskapp:
	image: fishaw1/flaskapp
	networks:
	    - app
    nginx:
	image: fishaw1/nginx
	ports:
	    - 8080:80
	networks:
	    - app
    redis:
	image: "redis:latest"
	networks:
	    - app
networks:
    app:
	image: overlay
