#Aiden Fisher
version: '3'
services:
	flaskapp:
		build: ./flaskapp
		image: flaskapp
		networks:
		    - app
	nginx:
		build: ./nginx
		image: nginx
		ports:
		    - 8080:80
		networks:
		    - app
		depends_on:
		    - flaskapp
	redis:
		image: "redis:alpine"
networks:
	app:
